project/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
   url(r'project/create$', 'project.views.create_project', name='project.create'),
   url(r'project/(\d+)$', 'project.views.project_detail', name='project.detail'),
   url(r'project/$', 'project.views.project_list', name='project.list'),

   url(r'project/(\d+)/create-task$', 'project.views.task_create', name='task.create'),
   url(r'task/(\d+)$', 'project.views.task_detail', name='task.detail'),
   url(r'task/(\d+)/assign-user$', 'project.views.assign_user', name='task.assign_user'),
   url(r'task/(\d+)/start', 'project.views.start_task', name='task.start'),
   url(r'task/(\d+)/resolve', 'project.views.resolve_task', name='task.resolve'),
   url(r'task/(\d+)/close', 'project.views.close_task', name='task.close'),
   url(r'task/(\d+)/comment', 'project.views.comment_task', name='task.comment'),
   url(r'project/(\d+)/tasks/$', 'project.views.task_list', name='task.list'),
)

scrum/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'scrum.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('project.urls')),
    url(r'^$', RedirectView.as_view(url='/project/', permanent=False), name='index'),
)

project/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Project(models.Model):
    shortcut = models.CharField(max_length=3)
    name = models.CharField(max_length=30)

    def change_name(self, name):
        self.name = name

    def change_shortcut(self, shortcut):
        self.shortcut = shortcut

    def plan_sprint(self, start, end, tasks):
        sprint = Sprint(project=self, start=start, end=end)

        for task in tasks:
            task.assign_to_sprint(sprint)

        return sprint

    def create_task(self, name, description):
        task = Task(
            project=self, name=name, description=description
        )

        return task

    def __unicode__(self):
        return self.name


class Sprint(models.Model):
    project = models.ForeignKey(Project)
    start = models.DateField()
    end = models.DateField()


class Task(models.Model):
    project = models.ForeignKey(Project)
    sprint = models.ForeignKey(Sprint, null=True)

    name = models.CharField(max_length=100)
    description = models.TextField(max_length=10000, null=True)

    assigned_user = models.ForeignKey(User, null=True)
    started = models.DateTimeField(null=True)
    resolved = models.DateTimeField(null=True)
    closed = models.DateTimeField(null=True)

    resolution = models.TextField(null=True)

    def assign_to(self, user_id):
        self.assigned_user_id = user_id

    def start(self, date):
        if not self.started:
            self.started = date

    def resolve(self, date, resolution):
        if not self.resolved:
            self.resolved = date
            self.resolution = resolution

    def close(self, date):
        if not self.closed:
            self.closed = date

    def comment(self, author_id, message):
        return Comment(author_id=author_id, message=message, task=self)

    def assign_to_sprint(self, sprint):
        if not self.sprint:
            self.sprint = sprint

    @property
    def is_started(self):
        return not self.is_resolved and self.started is not None

    @property
    def is_resolved(self):
        return not self.is_closed and self.resolved is not None

    @property
    def is_closed(self):
        return self.closed is not None



class Comment(models.Model):
    author = models.ForeignKey(User)
    task = models.ForeignKey(Task)
    message = models.TextField()

    @property
    def author_name(self):
        return self.author.get_full_name() or self.author.username

project/views.py
from django import forms
from django.contrib.auth.models import User

from django.forms.models import modelform_factory
from django.shortcuts import render, redirect, resolve_url

from project.application import Application, DjangoRepository
from project.models import Project, Task


ProjectForm = modelform_factory(Project, fields=['shortcut', 'name'])

app = Application(DjangoRepository())

# Create your views here.
def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)

        if form.is_valid():
            project_id = app.project_service.create_project(**form.cleaned_data)
            return redirect(resolve_url('project.detail', project_id))
    else:
        form = ProjectForm()

    return render(request, 'project/project_create.html', {'form': form})


def project_detail(request, project_id):
    project = app.project_service.read_project(project_id)

    form = ProjectForm(instance=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)

        if form.is_valid():
            app.project_service.update_project(project_id, **form.cleaned_data)
            return redirect(resolve_url('project.detail', project_id))

    return render(request, 'project/project_detail.html', {'form': form})


def project_list(request):
    projects = app.project_service.list_projects()
    return render(request, 'project/project_list.html', {'projects': projects})


TaskForm = modelform_factory(Task, fields=['name', 'description'])
AssignUserForm = modelform_factory(Task, fields=['assigned_user'])

def task_create(request, project_id):
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            task_id = app.task_service.create_task(
                project_id, **form.cleaned_data
            )

            return redirect(resolve_url('task.detail', task_id))

    return render(request, 'task/task_create.html', {'form': form})


def task_detail(request, task_id):
    task = app.task_service._read_task(task_id)


    form = TaskForm(instance=task)
    assigned_form = AssignUserForm(instance=task)
    comments = app.task_service.list_task_comments(task_id)
    comment_form = CommentTaskForm()

    return render(request, 'task/task_detail.html', {
        'task': task,
        'form': form,
        'assigned_form': assigned_form,
        'comments': comments,
        'comment_form': comment_form
    })


def assign_user(request, task_id):
    task = app.task_service._read_task(task_id)

    if request.method == 'POST':
        form = AssignUserForm(request.POST, instance=task)

        if form.is_valid():
            app.task_service.assign_task(task_id, form.cleaned_data['assigned_user'].pk)

    return redirect(resolve_url('task.detail', task_id))

def start_task(request, task_id):
    app.task_service.start_task(task_id)
    return redirect(resolve_url('task.detail', task_id))

class ResolveTaskForm(forms.Form):
    resolution = forms.CharField(widget=forms.Textarea())

def resolve_task(request, task_id):
    form = ResolveTaskForm()

    if request.method == 'POST':
        form = ResolveTaskForm(request.POST)
        if form.is_valid():
            app.task_service.resolve_task(task_id, form.cleaned_data['resolution'])
            return redirect(resolve_url('task.detail', task_id))

    return render(request, 'task/task_resolve.html', {'form': form})

def close_task(request, task_id):
    app.task_service.close_task(task_id)
    return redirect(resolve_url('task.detail', task_id))

class CommentTaskForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea())

def comment_task(request, task_id):
    form = CommentTaskForm()

    if request.method == 'POST':
        form = CommentTaskForm(request.POST)
        if form.is_valid():
            app.task_service.comment_task(task_id, request.user.pk, form.cleaned_data['message'])

    return redirect(resolve_url('task.detail', task_id))

def task_list(request, project_id):
    tasks = app.task_service.list_project_tasks(project_id)

    return render(request, 'task/task_list.html', {
        'tasks': tasks
    })

project/templates/project/project_create.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block container %}
    <div class="col-md-4 col-md-offset-4 well">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Create project
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

project/templates/project/project_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block container %}
    <div class="col-md-4 col-md-offset-4 well">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Update
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

project/templates/project/project_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block container %}
    <a href="{% url "project.create"  %}" class="btn btn-primary">New project</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <td>Shortcut</td>
            <td>Name</td>
            <td></td>
        </tr>
        </thead>
        <tbody>
        {% for project in projects %}
            <tr>
                <td>
                    <a href="{% url 'project.detail' project.pk %}">
                        {{ project.shortcut }}
                    </a>
                </td>
                <td>{{ project.name }}</td>
                <td>
                    <ul class="list-unstyled list-inline">
                        <li>
                            <a href="{% url 'task.create' project.pk %}"> Create task </a>
                        </li>
                        <li>
                            <a href="{% url 'task.list' project.pk %}"> List task </a>
                        </li>
                    </ul>

                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

project/templates/task/task_create.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block container %}
    <div class="col-md-4 col-md-offset-4 well">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Create task
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

project/templates/task/task_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
    $(function() {
       $("#id_assigned_user").on('change', function() {
          $(this).parents('form').submit();
       });
    });
    </script>
{% endblock %}

{% block container %}
    <div>
        <h3>{{ task.name }}</h3>

        <div class="row">
            <div class="col-md-2">Status:</div>
            <div class="col-md-10">
                {% if task.is_closed %}
                    Closed
                {% elif task.is_resolved %}
                    <form action="{% url 'task.close' task.pk %}" method="post">
                        {% csrf_token %}
                        Resolved
                        <button type="submit" class="btn btn-danger">Close task</button>
                    </form>
                {% elif task.is_started %}
                        Started
                        <a href="{% url 'task.resolve' task.pk %}" class="btn btn-danger">Resolve task</a>
                {% else %}
                    <form action="{% url 'task.start' task.pk %}" method="post">
                        {% csrf_token %}
                        Unplaned
                        <button type="submit" class="btn btn-danger">Start task</button>
                    </form>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">Assignee:</div>
            <div class="col-md-4">
                <form method="post" action="{% url 'task.assign_user' task.pk %}">
                    {% csrf_token %}
                    {% bootstrap_form assigned_form layout='inline' %}
                </form>
            </div>
        </div>


        <p class="well-small well">{{ task.description }}</p>
    </div>

    <hr/>
    <h4>Comments:</h4>
    <dt>
        {% for comment in comments %}
        <dt>{{ comment.author_name }}:</dt>
        <dd>{{ comment.message }}</dd>
        {% endfor %}

        <dt>
            {% if request.user.get_full_name %}
                {{ request.user.get_full_name }}
            {% else %}
                {{ request.user.username }}
            {% endif %}:
        </dt>
        <dd>
            <form action="{% url 'task.comment' task.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form comment_form layout='inline' %}
                {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Comment
                </button>
            {% endbuttons %}
            </form>
        </dd>
    </dt>
{% endblock %}

project/templates/task/task_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block container %}
    <table class="table table-striped">
        <thead>
        <tr>
            <td>Name</td>
            <td>Status</td>
        </tr>
        </thead>
    <tbody>
    {% for task in tasks %}
        <tr>
            <td>
                <a href="{% url 'task.detail' task.pk %}">
                    {{ task.name }}
                </a>
            </td>
            <td>
                {% if task.is_closed %}
                    Closed
                {% elif task.is_resolved %}
                    Resolved
                {% elif task.is_started %}
                    Started
                {% else %}
                    Unplaned
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

project/templates/task/task_resolve.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block container %}
    <div class="col-md-4 col-md-offset-4 well">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    Resolve task
                </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

templates/base.html
{% extends "bootstrap.html" %}

{% block navbar %}
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Scrum</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'project.list' %}">Projects</a></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
{% endblock %}

{% block content %}
    <div class="container">
    {% block container %}
    {% endblock %}
    </div>
{% endblock %}

templates/bootstrap.html
{% load staticfiles %}
{% load bootstrap3  %}
{% block doc %}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{% block html %}
  <head>
    {% block head %}
    <title>{% block title %}{% endblock title %}</title>

    {% block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock metas %}

    {% block styles %}
    <!-- Bootstrap -->
{#    <link href="{% static "bootstrap/dist/css/bootstrap.css" %}" rel="stylesheet" media="screen">#}
        {% bootstrap_css %}
    {% endblock styles %}
    {% endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body %}
    {% block navbar %}
    {% endblock navbar %}

    {% bootstrap_messages %}

    {% block content %}
    {% endblock content %}

    {% block scripts %}
        {% bootstrap_javascript jquery=1 %}
{#    <script src="{% static "jquery/src/jquery.js" %}"></script>#}
{#    <script src="{% static "bootstrap/dist/js/bootstrap.js" %}"></script>#}
    {% endblock scripts %}
    {% endblock body %}
  </body>
{% endblock html %}
</html>
{% endblock doc %}